### ISSUE TITLE
Can it be that wrong `.d.ts` files got published to `npm` with the latest version?

### ISSUE THREAD

**Issue by mrazauskas** [jest-community/create-jest-runner#116]
The `.d.ts` files look strange in latest version (0.11.0). Can it be something wrong got published to `npm`?

For instance, [`types.ts` in the repo](https://github.com/jest-community/create-jest-runner/blob/main/lib/types.ts) does not import from `'@jest/types'` anymore and it does not have types `Milliseconds`, or `Path`. But here is what I see installing the package and looking at `types.d.ts` (this is the whole file):

<img width="814" alt="Screenshot 2022-05-15 at 21 07 14" src="https://user-images.githubusercontent.com/72159681/168487584-646b4af5-60f3-48f3-80db-522a0031cb41.png">

I was trying to use the new `RunTest` type, but it is not there.

The installed version is 0.11.0. I checked three times, but who knows (;

**Comment by SimenB** [comment]
https://github.com/jest-community/create-jest-runner/releases/tag/v0.11.1
