### ISSUE TITLE
Identifying the running process

### ISSUE THREAD

**Issue by manu-st** [jest-community/create-jest-runner#19]
I'm using successfully the create-jest-runner however the processes I launch needs a unique socket port. Because I'm not able to get the first available port as I do not control the code of the process being launched, however I can pass as argument a port. All my processes thus need a different port.

To do that with create-jest-runner I would need to know which instance I have to use the right port. I was thinking of modifying create-jest-runner so to add to the extra options or add another option that would provide the ID of the runner between 1 and maxWorkers.

Is this something that you would be interested in?

**Comment by SimenB** [comment]
We already inject `JEST_WORKER_ID` as an env variable. Is that enormous for your use case?

**Comment by manu-st** [comment]
I had no idea about this environment variable. Thanks a lot for the tip. I'll close the issue if it works for me.

**Comment by manu-st** [comment]
It does work as intended. Thanks!
