### ISSUE TITLE
Remove mocha

### ISSUE THREAD

**Issue by milesj** [jest-community/create-jest-runner#9]
Noticed mocha being added to my lock file, and this repo is the culprit. Not sure why this requires mocha when I see no usages? Nor why it's a production dep.

**Comment by SimenB** [comment]
Yeah, sorry about that one. See #1

**Comment by rogeliog** [comment]
Yeah!

**Comment by rogeliog** [comment]
I just published `0.3.1`

**Comment by milesj** [comment]
Awesome, thanks so much!
